### ISSUE TITLE
Auto install nfs guest

### ISSUE THREAD

**Issue by frosit** [ByteInternet/hypernode-vagrant#103]
when selecting nfs_guest, a plugin is required. This is not installed automatically nor listed in the documentation. Results in the following error:

> /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builtin/mixin_synced_folders.rb:137:in `block in synced_folders': Internal error. Report this as a bug. Invalid: nfs_guest (RuntimeError)
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builtin/mixin_synced_folders.rb:125:in `each'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builtin/mixin_synced_folders.rb:125:in `synced_folders'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builtin/synced_folder_cleanup.rb:19:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/synced_folders/nfs/action_cleanup.rb:25:in `call'
etc...

Easily fixed by running `vagrant plugin install vagrant-nfs_guest`

Using this repo : [nfs_guest](https://github.com/Learnosity/vagrant-nfs_guest)

Maybe we can provide auto install or enhance documentation.

**Comment by peterjaap** [comment]
In addition to this, I also had to uninstall bindfs because it gave me an undefined constant `VagrantPlugins::Bindfs::SOURCE_VERSION` warning. In hindsight maybe updating it also should've worked.
