### ISSUE TITLE
Vagrant up

### ISSUE THREAD

**Issue by Onderbroeken** [ByteInternet/hypernode-vagrant#110]
Goedenavond,

Ik krijg steeds de volgende foutmelding:

<img width="571" alt="schermafbeelding 2016-11-09 om 23 45 05" src="https://cloud.githubusercontent.com/assets/23367236/20157696/a83ed1a0-a6d6-11e6-9b0a-1338e678a712.png">

Hoe krijg ik dit verholpen, aangezien er geen verdere errors te voorschijn komen.

**Comment by vdloo** [comment]
Hi,

Are you on Windows 10 by any chance? I think that in some cases the `application/json` content type might not be properly recognized. Does it fail repeatedly? Have you tried updating Vagrant? What version are you running?

**Comment by Onderbroeken** [comment]
This problem is solved, but unfortunately I have some other errors:

Bringing machine 'hypernode' up with 'virtualbox' provider...
/opt/vagrant/embedded/lib/ruby/2.2.0/psych.rb:464:in `initialize': No such file or directory @ rb_sysopen - .local.base.yml (Errno::ENOENT)
	from /opt/vagrant/embedded/lib/ruby/2.2.0/psych.rb:464:in `open'
	from /opt/vagrant/embedded/lib/ruby/2.2.0/psych.rb:464:in `load_file'
	from /Users/Steven/.vagrant.d/gems/2.2.5/gems/vagrant-hypconfigmgmt-0.0.5/lib/vagrant-hypconfigmgmt/command.rb:65:in `rescue in retrieve_settings'
	from /Users/Steven/.vagrant.d/gems/2.2.5/gems/vagrant-hypconfigmgmt-0.0.5/lib/vagrant-hypconfigmgmt/command.rb:62:in `retrieve_settings'
	from /Users/Steven/.vagrant.d/gems/2.2.5/gems/vagrant-hypconfigmgmt-0.0.5/lib/vagrant-hypconfigmgmt/command.rb:374:in `ensure_settings_configured'
	from /Users/Steven/.vagrant.d/gems/2.2.5/gems/vagrant-hypconfigmgmt-0.0.5/lib/vagrant-hypconfigmgmt/command.rb:50:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:225:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:200:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/environment.rb:567:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:186:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/machine.rb:186:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.1/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'

I followed the steps provided in Readme file.

I'm using macOS Sierra.

**Comment by vdloo** [comment]
Hi,

Are you running `vagrant up` in the `hypernode-vagrant` directory?

For example, running it in the `hypernode-vagrant/vagrant` directory will result in the error you show.

```
~/code/projects/hypernode-vagrant/vagrant$ vagrant up 
Bringing machine 'hypernode' up with 'virtualbox' provider...
/opt/vagrant/embedded/lib/ruby/2.2.0/psych.rb:464:in `initialize': No such file or directory @ rb_sysopen - .local.base.yml (Errno::ENOENT)
```

Instead, run `vagrant up` in the directory where the Vagrantfile is (the `hypernode-vagrant` directory).

```
~/code/projects/hypernode-vagrant$ cd ~/code/projects/hypernode-vagrant
~/code/projects/hypernode-vagrant$ vagrant up 
Bringing machine 'hypernode' up with 'virtualbox' provider...
==> hypernode: Will use PHP 7. If you want PHP 5.5 instead change the php version in local.yml.
==> hypernode: Checking if box 'hypernode_php7' is up to date...
...
```

If it still fails then you should verify if the `.local.base.yml` exists in your checkout.

```
~/code/projects/hypernode-vagrant$ ls -la
total 84
drwxrwxr-x  9 vdloo vdloo  4096 nov 29 09:06 .
drwxrwxr-x 87 vdloo vdloo  4096 nov 26 13:58 ..
drwxrwxr-x  3 vdloo vdloo  4096 mei  7  2016 data
drwxrwxr-x  2 vdloo vdloo  4096 mei  7  2016 Documentation
drwxrwxr-x  4 vdloo vdloo  4096 nov 21 07:16 examples
drwxrwxr-x  6 vdloo vdloo  4096 dec  7 23:07 .git
drwxrwxr-x  3 vdloo vdloo  4096 nov 20 12:22 tools
drwxrwxr-x  5 vdloo vdloo  4096 jul  6 15:26 vagrant
drwxrwxr-x  4 vdloo vdloo  4096 okt 22 22:31 .vagrant
-rw-rw-r--  1 vdloo vdloo   436 aug  6 11:58 composer.json
-rw-rw-r--  1 vdloo vdloo   105 aug  6 11:58 .gitignore
-rw-rw-r--  1 vdloo vdloo   328 jul  6 15:26 .local.base.yml  # This one
-rw-rw-r--  1 vdloo vdloo   607 dec  7 23:06 local.yml
-rw-rw-r--  1 vdloo vdloo 13000 okt  4 21:41 README.md
-rwxrwxr-x  1 vdloo vdloo   573 nov 20 12:22 runtests.sh
-rw-rw-r--  1 vdloo vdloo   158 aug  6 11:58 .travis.yml
-rw-rw-r--  1 vdloo vdloo  7541 nov 29 09:06 Vagrantfile
```

If it does not, run `git status` to see the changes you made to the repository. You can always reset it using `git reset --hard origin/master`

**Comment by Onderbroeken** [comment]
I followed the steps in the readme file in hypernode-vagrant > examples > magento2_development_environment

make devenv should set up a Magento 2 development environment, right? 

scripts/deploy_development.sh
VM must be created before running this command. Run `vagrant up` first.
Registered ip: 
No config file found; using defaults
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY RECAP *********************************************************************

So, I run 'Vagrant up' but then I receive those errors mentioned before.

**Comment by vdloo** [comment]
Hi,

The `hypernode-vagrant > examples > magento2_development_environment` instructions are more of an example for how to set up automation around the Vagrant. For example if you already have a Magento 2 project and want to build a CI pipeline around it using the hypernode-vagrant. 

I'm assuming you don't want that and just want to set up a Magento 2 installation in the Vagrant. If that is the case, you can just create a checkout of the repository, run `vagrant up` and follow the dialogue. Once the instance is running you should then be able to log in using ssh and follow the steps in [this article here](https://support.hypernode.com/knowledgebase/installing-magento-2-on-hypernode/).

```
vdloo@workstation4:~/Downloads$ mkdir mag2install
vdloo@workstation4:~/Downloads$ cd mag2install/
vdloo@workstation4:~/Downloads/mag2install$ git clone https://github.com/ByteInternet/hypernode-vagrant
vdloo@workstation4:~/Downloads/mag2install$ cd hypernode-vagrant/
vdloo@workstation4:~/Downloads/mag2install/hypernode-vagrant$ vagrant up 
Bringing machine 'hypernode' up with 'virtualbox' provider...
    hypernode: Is this a Magento 1 or 2 Hypernode? [default 2]: 
==> hypernode: Nginx will be configured for Magento 2. /data/web/magento2/pub will be symlinked to /data/web/public
    hypernode: Is this a PHP 5.5 or 7.0 Hypernode? [default 7.0]: 
==> hypernode: Will boot a box with PHP 7.0 installed
    hypernode: Do you want to enable Varnish? Enter true or false [default false]: 
==> hypernode: Varnish will be disabled by loading a nocache vcl.
    hypernode: What filesystem type do you want to use? Options: nfs_guest, nfs, rsync, virtualbox [default virtualbox]: 
==> hypernode: Virtualbox is the default fs type. If you later want to try a faster fs type like nfs_guest, edit local.yml
==> hypernode: Disabling fs->folders->magento1 in the local.yml because Magento 2 was configured..
    hypernode: Do you want to enable the production-like firewall? Enter true or false [default false]: 
==> hypernode: The firewall will be disabled
    hypernode: Do you want to enable production-like memory management? 
    hypernode: This might be slower but it is more in-line with a real Hypernode. 
    hypernode: Note: for LXC boxes this setting is disabled. 
    hypernode: Enter true or false [default false]: 
==> hypernode: Production-like memory management will be disabled
    hypernode: Do you want to install Xdebug? Enter true or false [default false]: 
==> hypernode: Xdebug will be disabled
==> hypernode: Will use PHP 7. If you want PHP 5.5 instead change the php version in local.yml.
==> hypernode: Your hypernode-vagrant is now configured. Please run "vagrant up" again.
vdloo@workstation4:~/Downloads/mag2install/hypernode-vagrant$ vagrant up 
Bringing machine 'hypernode' up with 'virtualbox' provider...
==> hypernode: Will use PHP 7. If you want PHP 5.5 instead change the php version in local.yml.
==> hypernode: Importing base box 'hypernode_php7'...
...
==> hypernode: Your hypernode-vagrant is ready! Log in with:
==> hypernode: ssh app@hypernode.local -oStrictHostKeyChecking=no -A
==> hypernode: Or visit http://mag2install.hypernode.local in your browser
vdloo@workstation4:~/Downloads/mag2install/hypernode-vagrant$ vagrant ssh
Welcome to Ubuntu 12.04.3 LTS (GNU/Linux 3.13.0-100-generic x86_64)

 * Documentation:  https://help.ubuntu.com/
New release '14.04.5 LTS' available.
Run 'do-release-upgrade' to upgrade to it.

Welcome to your Vagrant-built virtual machine.
Last login: Wed Jun 29 11:18:11 2016 from 10.0.2.2
vagrant@9b2822-mag2install-magweb-vgr:~$ sudo su
root@9b2822-mag2install-magweb-vgr /home/vagrant # su app
app@9b2822-mag2install-magweb-vgr:/home/vagrant$ cd 
app@9b2822-mag2install-magweb-vgr:~$ ls
disabled_caching.vcl  incidents  magento2  nginx  public  staging
app@9b2822-mag2install-magweb-vgr:~$ echo "now you can just follow the Magento 2 installation instructions"
now you can just follow the Magento 2 installation instructions
```
https://support.hypernode.com/knowledgebase/installing-magento-2-on-hypernode/

If you however do actually want to use the magento2_development_environment example and you want to script some stuff around the Vagrant, maybe you can draw some inspiration from the output below. I've walked through the README and it looks like there are some hurdles. For example you need to have an up to date version of Ansible and it is not documented anywhere that you need to create your own local.yml beforehand to run the script.

```
# Create a fresh checkout
vdloo@workstation4:~$ cd Downloads/
vdloo@workstation4:~/Downloads$ mkdir mag2devenv
vdloo@workstation4:~/Downloads$ cd mag2devenv/
vdloo@workstation4:~/Downloads/mag2devenv$ git clone https://github.com/ByteInternet/hypernode-vagrant
Cloning into 'hypernode-vagrant'...
remote: Counting objects: 913, done.
remote: Total 913 (delta 0), reused 0 (delta 0), pack-reused 913
Receiving objects: 100% (913/913), 771.46 KiB | 374.00 KiB/s, done.
Resolving deltas: 100% (430/430), done.
Checking connectivity... done.
vdloo@workstation4:~/Downloads/mag2devenv$ cd hypernode-vagrant/

# Put the Magento marketplace credentials and the admin password in your environment
vdloo@workstation4:~/Downloads/mag2devenv/hypernode-vagrant$ export MAGENTO_MARKETPLACE_PUBLIC_KEY=<YOURPUBLICKEY>
vdloo@workstation4:~/Downloads/mag2devenv/hypernode-vagrant$ export MAGENTO_MARKETPLACE_PRIVATE_KEY=<YOURPRIVATEKEY>
vdloo@workstation4:~/Downloads/mag2devenv/hypernode-vagrant$ export MAGENTO_ADMIN_PASSWORD=admin1234


# Install Ansible in a python virtualenv
vdloo@workstation4:~/Downloads/mag2devenv/hypernode-vagrant$ cd examples/magento2_development_environment/
vdloo@workstation4:~/Downloads/mag2devenv/hypernode-vagrant/examples/magento2_development_environment$ [ ! -d venv ] && virtualenv venv
Running virtualenv with interpreter /usr/bin/python2
New python executable in /home/vdloo/Downloads/mag2devenv/hypernode-vagrant/examples/magento2_development_environment/venv/bin/python2
Also creating executable in /home/vdloo/Downloads/mag2devenv/hypernode-vagrant/examples/magento2_development_environment/venv/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
vdloo@workstation4:~/Downloads/mag2devenv/hypernode-vagrant/examples/magento2_development_environment$ venv/bin/pip install ansible
Collecting ansible
Collecting PyYAML (from ansible)
Requirement already satisfied: setuptools in ./venv/lib/python2.7/site-packages (from ansible)
Collecting jinja2 (from ansible)
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Collecting paramiko (from ansible)
  Using cached paramiko-2.0.2-py2.py3-none-any.whl
Collecting pycrypto>=2.6 (from ansible)
Collecting MarkupSafe (from jinja2->ansible)
Collecting pyasn1>=0.1.7 (from paramiko->ansible)
  Using cached pyasn1-0.1.9-py2.py3-none-any.whl
Collecting cryptography>=1.1 (from paramiko->ansible)
Collecting ipaddress (from cryptography>=1.1->paramiko->ansible)
  Using cached ipaddress-1.0.17-py2-none-any.whl
Collecting six>=1.4.1 (from cryptography>=1.1->paramiko->ansible)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting enum34 (from cryptography>=1.1->paramiko->ansible)
  Using cached enum34-1.1.6-py2-none-any.whl
Collecting idna>=2.0 (from cryptography>=1.1->paramiko->ansible)
  Using cached idna-2.1-py2.py3-none-any.whl
Collecting cffi>=1.4.1 (from cryptography>=1.1->paramiko->ansible)
  Using cached cffi-1.9.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting pycparser (from cffi>=1.4.1->cryptography>=1.1->paramiko->ansible)
Installing collected packages: PyYAML, MarkupSafe, jinja2, pyasn1, ipaddress, six, enum34, idna, pycparser, cffi, cryptography, paramiko, pycrypto, ansible
Successfully installed MarkupSafe-0.23 PyYAML-3.12 ansible-2.2.0.0 cffi-1.9.1 cryptography-1.6 enum34-1.1.6 idna-2.1 ipaddress-1.0.17 jinja2-2.8 paramiko-2.0.2 pyasn1-0.1.9 pycparser-2.17 pycrypto-2.6.1 six-1.10.0
vdloo@workstation4:~/Downloads/mag2devenv/hypernode-vagrant/examples/magento2_development_environment$ . venv/bin/activate


# Configure the `hypernode-vagrant` using a local.xml configuration file. Edit local.yml with content like this:
(venv) vdloo@workstation4:~/Downloads/mag2devenv/hypernode-vagrant/examples/magento2_development_environment$ vim local.yml
---
fs:
  folders:
    magento2:
      host: data/web/magento2
      guest: "/data/web/magento2"
    nginx:
      host: data/web/nginx/
      guest: "/data/web/nginx/"
  type: virtualbox
  disabled_folders:
    magento1:
      host: data/web/public
      guest: "/data/web/public"
hostmanager:
  extra-aliases:
  - my-custom-store-url1.local
  - my-custom-store-url2.local
magento:
  version: 2
php:
  version: 7.0
varnish:
  state: false
firewall:
  state: false
cgroup:
  state: false
xdebug:
  state: false
vagrant:
  box: hypernode_php7
  box_url: http://vagrant.hypernode.com/customer/php7/catalog.json


# Provision a development environment
(venv) vdloo@workstation4:~/Downloads/mag2devenv/hypernode-vagrant/examples/magento2_development_environment$ make devenv
scripts/check_env.sh
scripts/boot_vagrant.sh
vagrant-vbguest (0.13.0)
vagrant-hostmanager (1.8.5)
Cloning into 'hypernode-vagrant'...
remote: Counting objects: 913, done.
remote: Total 913 (delta 0), reused 0 (delta 0), pack-reused 913
Receiving objects: 100% (913/913), 771.46 KiB | 850.00 KiB/s, done.
Resolving deltas: 100% (430/430), done.
Checking connectivity... done.
==> hypernode: Checking for updates to 'hypernode_php7'
    hypernode: Latest installed version: 3455
    hypernode: Version constraints: 
    hypernode: Provider: virtualbox
==> hypernode: Box 'hypernode_php7' (v3455) is running the latest version.
Bringing machine 'hypernode' up with 'virtualbox' provider...
==> hypernode: Will use PHP 7. If you want PHP 5.5 instead change the php version in local.yml.
==> hypernode: Importing base box 'hypernode_php7'...
==> hypernode: Matching MAC address for NAT networking...
==> hypernode: Checking if box 'hypernode_php7' is up to date...
==> hypernode: Setting the name of the VM: hypernode-vagrant_hypernode_1481188589435_36104
==> hypernode: Clearing any previously set network interfaces...
==> hypernode: Preparing network interfaces based on configuration...
    hypernode: Adapter 1: nat
    hypernode: Adapter 2: hostonly
==> hypernode: Forwarding ports...
    hypernode: 80 (guest) => 8080 (host) (adapter 1)
    hypernode: 3306 (guest) => 3307 (host) (adapter 1)
    hypernode: 22 (guest) => 2222 (host) (adapter 1)
==> hypernode: Running 'pre-boot' VM customizations...
==> hypernode: Booting VM...
==> hypernode: Waiting for machine to boot. This may take a few minutes...
    hypernode: SSH address: 127.0.0.1:2222
    hypernode: SSH username: vagrant
    hypernode: SSH auth method: private key
    hypernode: 
    hypernode: Vagrant insecure key detected. Vagrant will automatically replace
    hypernode: this with a newly generated keypair for better security.
    hypernode: 
    hypernode: Inserting generated public key within guest...
    hypernode: Removing insecure key from the guest if it's present...
    hypernode: Key inserted! Disconnecting and reconnecting using new SSH key...
==> hypernode: Machine booted and ready!
[hypernode] GuestAdditions 5.0.26 running --- OK.
==> hypernode: Checking for guest additions in VM...
==> hypernode: Setting hostname...
==> hypernode: Configuring and enabling network interfaces...
==> hypernode: Mounting shared folders...
    hypernode: /vagrant => /home/vdloo/Downloads/mag2devenv/hypernode-vagrant/examples/magento2_development_environment/hypernode-vagrant
    hypernode: /data/web/nginx => /home/vdloo/Downloads/mag2devenv/hypernode-vagrant/examples/magento2_development_environment/hypernode-vagrant/data/web/nginx
    hypernode: /data/web/magento2 => /home/vdloo/Downloads/mag2devenv/hypernode-vagrant/examples/magento2_development_environment/magento2
==> hypernode: Updating /etc/hosts file on active guest machines...
==> hypernode: Updating /etc/hosts file on host machine (password may be required)...
==> hypernode: Running provisioner: shell...
    hypernode: Running: /tmp/vagrant-shell20161208-5693-1uylsnt.sh
==> hypernode: stdin: is not a tty
==> hypernode:  * Starting HTTP accelerator varnishd
==> hypernode:    ...done.
==> hypernode: VCL compiled.
==> hypernode: VCL 'nocache' now active
==> hypernode: Your hypernode-vagrant is ready! Log in with:
==> hypernode: ssh app@hypernode.local -oStrictHostKeyChecking=no -A
==> hypernode: Or visit http://dummytag.hypernode.local in your browser
scripts/deploy_development.sh
Registered ip: 172.28.128.3
Using /etc/ansible/ansible.cfg as config file

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [172.28.128.3]

TASK [ensure composer directory exists] ****************************************
changed: [172.28.128.3] => {"changed": true, "gid": 1003, "group": "app", "mode": "0775", "owner": "app", "path": "/data/web/.composer", "size": 4096, "state": "directory", "uid": 1001}

TASK [store credentials for repo.magento.com] **********************************
changed: [172.28.128.3] => {"changed": true, "checksum": "fsafdsafdsafsda", "dest": "/data/web/.composer/auth.json", "gid": 1003, "group": "app", "md5sum": "fdsafdsafdsafdsa", "mode": "0664", "owner": "app", "size": 189, "src": "/data/web/.ansible/tmp/ansible-tmp-1481188623.57-125309552222340/source", "state": "file", "uid": 1001}

TASK [install or update composer dependencies (takes a while)] *****************
...
```

**Comment by Onderbroeken** [comment]
Yeah, that solved the problem! Now it works like a charm, but localhost is very slow. Sometimes I have to wait for 3 minutes to load a page which is frustrating. Any idea how to speed up virtualbox?

**Comment by tomlankhorst** [comment]
- Enable caching
- Configure Redis
- Configure Varnish
- Use NFS or NFS-guest for sharing files 
- Disable production specific modules
- Use PHP7
- Increase the amount of CPU's and MEM in your VirtualBox.

**Comment by Onderbroeken** [comment]
Everythime I run 'vagrant up' I see the standard Hypernode dev window: Your Hypernode test environment is ready for use... etc

So, when I get that message I re-install magento everytime but of course that's time consuming. What do I have to do when I want to access the magento 2 webshop after closing localhost tab?

**Comment by vdloo** [comment]
Closing the browser tab should have no effect on the site running on the virtual server. If you go to the same URL again when the Vagrant is still running you should reach the same website. If that is not the case there might be some local caching going on. You can try control + shift + r to refresh the page without using your browser cache. 

Note that if you do not install Magento in one of the shared folders it will be gone when you start a new instance. If you want to keep the same instance between sessions don't run `vagrant destroy` but instead `vagrant halt` or `vagrant suspend`. Running `vagrant up` then later will start the same VM again with the data intact. See: https://www.vagrantup.com/docs/getting-started/teardown.html

As for the 502, that could be many things. I suspect it has to do with a timeout because you stated that you experienced bad performance. Are you using an SSD? Like Tom said, it might be worth looking into vagrant-nfs_guest to speed up IO. If you get the 502 you could try logging in to the machine and inspect the logs (`vagrant ssh` and then `sudo su`, look in `/var/logs/nginx`). That might give you some better insight into what is going on.

**Comment by tomlankhorst** [comment]
Try to restart varnish as root:

On host: ~ vagrant ssh
On vm: ~sudo service varnishd restart
(or something alike)

**Comment by Onderbroeken** [comment]
So, I did the following and now I have the 502 Bad Gateway error again:

MacBook-Pro:hypernode-vagrant Steven$ vagrant halt
==> hypernode: Attempting graceful shutdown of VM...
==> hypernode: [vagrant-hostsupdater] Removing hosts
MacBook-Pro:hypernode-vagrant Steven$ 
MacBook-Pro:hypernode-vagrant Steven$ vagrant up
Bringing machine 'hypernode' up with 'virtualbox' provider...
==> hypernode: Will use PHP 7. If you want PHP 5.5 instead change the php version in local.yml.
==> hypernode: Checking if box 'hypernode_php7' is up to date...
==> hypernode: Clearing any previously set forwarded ports...
==> hypernode: Clearing any previously set network interfaces...
==> hypernode: Preparing network interfaces based on configuration...
    hypernode: Adapter 1: nat
    hypernode: Adapter 2: hostonly
==> hypernode: Forwarding ports...
    hypernode: 80 (guest) => 8080 (host) (adapter 1)
    hypernode: 3306 (guest) => 3307 (host) (adapter 1)
    hypernode: 22 (guest) => 2222 (host) (adapter 1)
==> hypernode: Running 'pre-boot' VM customizations...
==> hypernode: Booting VM...
==> hypernode: Waiting for machine to boot. This may take a few minutes...
    hypernode: SSH address: 127.0.0.1:2222
    hypernode: SSH username: vagrant
    hypernode: SSH auth method: private key
==> hypernode: Machine booted and ready!
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   5.0.26
VBoxService inside the vm claims: 5.1.10
Going on, assuming VBoxService is correct...
[hypernode] GuestAdditions 5.1.10 running --- OK.
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   5.0.26
VBoxService inside the vm claims: 5.1.10
Going on, assuming VBoxService is correct...
==> hypernode: Checking for guest additions in VM...
    hypernode: The guest additions on this VM do not match the installed version of
    hypernode: VirtualBox! In most cases this is fine, but in rare cases it can
    hypernode: prevent things such as shared folders from working properly. If you see
    hypernode: shared folder errors, please make sure the guest additions within the
    hypernode: virtual machine match the version of VirtualBox you have installed on
    hypernode: your host and reload your VM.
    hypernode: 
    hypernode: Guest Additions Version: 5.0.26
    hypernode: VirtualBox Version: 5.1
==> hypernode: [vagrant-hostsupdater] Checking for host entries
==> hypernode: Setting hostname...
==> hypernode: Configuring and enabling network interfaces...
==> hypernode: Mounting shared folders...
    hypernode: /vagrant => /Users/Steven/Desktop/mag2devenv/hypernode-vagrant
    hypernode: /data/web/nginx => /Users/Steven/Desktop/mag2devenv/hypernode-vagrant/data/web/nginx
    hypernode: /data/web/magento2 => /Users/Steven/Desktop/mag2devenv/hypernode-vagrant/data/web/magento2
==> hypernode: Updating /etc/hosts file on active guest machines...
==> hypernode: Updating /etc/hosts file on host machine (password may be required)...
==> hypernode: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> hypernode: flag to force provisioning. Provisioners marked to run always will still run.
MacBook-Pro:hypernode-vagrant Steven$

**Comment by vdloo** [comment]
Perhaps your issue is related to https://github.com/ByteInternet/hypernode-vagrant/issues/114

**Comment by Onderbroeken** [comment]
This solved the issue:

```
root@e2bef6-mag2devenv-magweb-vgr /home/vagrant # pdstatus
{
    "errors": {
        "check_mysql": true, 
        "check_readonly_fs": true, 
        "check_redis": true, 
        "check_syms": true, 
        "check_varnish_proxy": false, 
        "check_zend_opcache": true
    }
}
root@e2bef6-mag2devenv-magweb-vgr /home/vagrant # service varnish restart
 * Stopping HTTP accelerator varnishd                                    [fail] 
 * Starting HTTP accelerator varnishd                                    [ OK ] 
```

When I try `vagrant halt` agian the same problem comes back. Everytime I have to do `service varnish restart`, what would be the solution?

**Comment by vdloo** [comment]
It looks like there is a bug in our provisioning script where the hostname is changed without restarting varnish. We symlink the [default hostname /var/lib/varnish directory](https://github.com/ByteInternet/hypernode-vagrant/blob/master/vagrant/provisioning/hypernode.sh#L46) to the new hostname but that does not seem to work as intended. Restarting varnish after changing the hostname should create a `/var/lib/varnish` subdir for the new hostname automatically so we should do that instead if we see that the correct dir is not there yet in `/var/lib/varnish`. I'm not sure why varnish won't start again after halting and bringing the box back up but it is probably related.

**Comment by Onderbroeken** [comment]
Right now I have the following issue:

```
MacBook-Pro:hypernode-vagrant Steven$ vagrant up
Bringing machine 'hypernode' up with 'virtualbox' provider...
==> hypernode: Will use PHP 7. If you want PHP 5.5 instead change the php version in local.yml.
==> hypernode: Checking if box 'hypernode_php7' is up to date...
==> hypernode: Clearing any previously set forwarded ports...
==> hypernode: Clearing any previously set network interfaces...
==> hypernode: Preparing network interfaces based on configuration...
    hypernode: Adapter 1: nat
    hypernode: Adapter 2: hostonly
==> hypernode: Forwarding ports...
    hypernode: 80 (guest) => 8080 (host) (adapter 1)
    hypernode: 3306 (guest) => 3307 (host) (adapter 1)
    hypernode: 22 (guest) => 2222 (host) (adapter 1)
==> hypernode: Running 'pre-boot' VM customizations...
==> hypernode: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "624f3978-ce5f-4726-90bf-83b1bcb747f7", "--type", "headless"]

Stderr: VBoxManage: error: Could not open the medium '/Users/Steven/VirtualBox VMs/hypernode-vagrant_hypernode_1482965140455_16416/box-disk1.vmdk'.
VBoxManage: error: VMDK: inconsistency between grain table and backup grain table in '/Users/Steven/VirtualBox VMs/hypernode-vagrant_hypernode_1482965140455_16416/box-disk1.vmdk' (VERR_VD_VMDK_INVALID_HEADER).
VBoxManage: error: VD: error VERR_VD_VMDK_INVALID_HEADER opening image file '/Users/Steven/VirtualBox VMs/hypernode-vagrant_hypernode_1482965140455_16416/box-disk1.vmdk' (VERR_VD_VMDK_INVALID_HEADER)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MediumWrap, interface IMedium
```

I've never had this issue before...

**Comment by vdloo** [comment]
Looks like your VM got corrupted. Did you perhaps power of your computer when it was running the last time? I guess that destroying the instance and creating a new one will rid of of that error.
