### ISSUE TITLE
There was an error executing lxc-attach

### ISSUE THREAD

**Issue by Aquive** [ByteInternet/hypernode-vagrant#178]
We are trying to use hypernode with lxc and we get the following error:
We're using Manjaro. 
```
Bringing machine 'hypernode' up with 'lxc' provider...
==> hypernode: Checking if box 'hypernode_xenial' is up to date...
==> hypernode: Fixed port collision for 22 => 2222. Now on port 2200.
==> hypernode: Setting up mount entries for shared folders...
    hypernode: /vagrant => /home/akif/Boxes/lxc
==> hypernode: Starting container...
==> hypernode: Waiting for machine to boot. This may take a few minutes...
There was an error executing ["sudo", "/usr/bin/env", "lxc-attach", "--name", "lxc_hypernode_1515163626562_40048", "--namespaces", "NETWORK|MOUNT", "--", "/sbin/ip", "-4", "addr", "show", "scope", "global", "eth0"]
```

**Comment by vdloo** [comment]
Hi @Aquive, it looks like vagrant is hiding the actual error. If you run `VAGRANT_LOG=debug vagrant up` you should get a more verbose output. However, LXC issues generally originate from system configurations and not our box. 'Officially' this box is for Ubuntu and I can imagine that on Manjaro there will be some occasional incompatibilities. Manjaro is based on Arch Linux and they have a more aggressive policy of updating software than Debian based distros so if you depend on LXC for important systems I recommend being very mindful to check if everything still works as you expect after package updates.

**Comment by Aquive** [comment]
Hi @vdloo thanks for your answer. I just reran it with the debug option set. It looks like the same error:

`...
/usr/lib/ruby/2.4.0/timeout.rb:108:in `timeout'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/plugins/communicators/ssh/communicator.rb:61:in `wait_for_ready'
/opt/vagrant/embedded/gems/gems/vagrant-2.0.1/lib/vagrant/action/builtin/wait_for_communicator.rb:16:in `block in call'
 INFO interface: error: There was an error executing ["sudo", "/usr/bin/env", "lxc-attach", "--name", "lxc_hypernode_1515163626562_40048", "--namespaces", "NETWORK|MOUNT", "--", "/sbin/ip", "-4", "addr", "show", "scope", "global", "eth0"]

For more information on the failure, enable detailed logging by setting
the environment variable VAGRANT_LOG to DEBUG.
There was an error executing ["sudo", "/usr/bin/env", "lxc-attach", "--name", "lxc_hypernode_1515163626562_40048", "--namespaces", "NETWORK|MOUNT", "--", "/sbin/ip", "-4", "addr", "show", "scope", "global", "eth0"]

For more information on the failure, enable detailed logging by setting
the environment variable VAGRANT_LOG to DEBUG.
 INFO interface: Machine: error-exit ["Vagrant::LXC::Errors::ExecuteError", "There was an error executing [\"sudo\", \"/usr/bin/env\", \"lxc-attach\", \"--name\", \"lxc_hypernode_1515163626562_40048\", \"--namespaces\", \"NETWORK|MOUNT\", \"--\", \"/sbin/ip\", \"-4\", \"addr\", \"show\", \"scope\", \"global\", \"eth0\"]\n\nFor more information on the failure, enable detailed logging by setting\nthe environment variable VAGRANT_LOG to DEBUG."]`

**Comment by vdloo** [comment]
You could try running the `"sudo", "/usr/bin/env", "lxc-attach", "--name", "lxc_hypernode_1515163626562_40048", "--namespaces", "NETWORK|MOUNT", "--", "/sbin/ip", "-4", "addr", "show", "scope", "global", "eth0"` command manually just around the moment the error would occur, perhaps that will show you the actual error.

**Comment by vdloo** [comment]
@Aquive perhaps it has something to do with your network bridge. Do you have one configured? For lxc it is often named lxcbr0

This will show you the interface
```
ip addr show lxcbr0
```

The default lxc-net config on ubuntu looks something like this: https://www.apt-browse.org/browse/ubuntu/trusty/main/i386/lxc/1.0.3-0ubuntu3/file/etc/init/lxc-net.conf

**Comment by AngelsDustz** [comment]
Alright so I found the cause of this issue.
When you create a vagrant box without having the Linux bridge `lxcbr0` configured it will initialize the box without the `eth0`. Then when hypernode (Or vagrant?) tries to start it sees the network address doesn't exist and will throw an error.

So before you clone the repository and run `vagrant up` one has to make sure the service `lxc-net` is running and has `lxcbro0` (Or how you configured it) and then run the initial `vagrant up`. This way your vagrant box will be configured with the bridge and `eth0` will be configured.

**Comment by vdloo** [comment]
Good to hear you figured it out @AngelsDustz!
